Translate file: /ceph/hpc/data/s24o01-42-users/translation_optimization/get_translations/translate_generic.py
python3 translate_generic.py               --model_path=GaMS-Beta/GaMS-9B-SFT-Translator               --input_module=/ceph/hpc/data/s24o01-42-users/translation_optimization/get_translations/load_data_scripts/load_nemotron.py               --output_path=test/translations_0.jsonl               --gpu_memory_util=0.95               --tp_size=1               --id=0
cpu-bind=MASK - ixh, task  0  0 [3357579]: mask 0xf000000000000000000000000000f0000000000000000 set
Found existing installation: vllm 0.10.1.1
Uninstalling vllm-0.10.1.1:
  Would remove:
    /usr/local/bin/vllm
    /usr/local/lib/python3.10/dist-packages/vllm-0.10.1.1.dist-info/*
    /usr/local/lib/python3.10/dist-packages/vllm/*
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 107, in _run_wrapper
    status = _inner_run()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 98, in _inner_run
    return self.run(options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/uninstall.py", line 105, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 726, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 367, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 407, in _allowed_to_proceed
    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 221, in ask
    response = input(message)
EOFError: EOF when reading a line
Proceed (Y/n)? srun: error: ixh: task 0: Exited with exit code 2
